version: '3.4'

services:
  db:
    container_name: MSSQL
    image: "mcr.microsoft.com/mssql/server:2019-latest"

  api:
    image: ${DOCKER_REGISTRY-}webstore-api
    depends_on:
      - db
    build:
        context: .
        dockerfile: Services/WebStore.WebAPI/Dockerfile

  webstore:
    image: ${DOCKER_REGISTRY-}webstore
    depends_on:
      - db
      - api    
    build:
      context: .
      dockerfile: UI/WebStore/Dockerfile
